### ISSUE TITLE
Load images, movies, or asciicasts from readmes

### ISSUE THREAD

**Issue by bennypowers** [rsbear/nvimluau#24]
You should load up graphics in readmes, many of which have gifs, .movs, or asciinema links

in the latter case, you could do better than github's ui by automatically embedding the movie from asciinema

**Comment by rsbear** [comment]
I totally agree. 
The problem is that a lot of repos READMEs are using paths to assets that are relative to that repo and I need a full URL in order to display them. I'm just downloading READMEs from a submitted repo and then letting a library do all of the parsing for me. 

I understand that's an audacious request for plugin authors though. So I could potentially go through the README on submit and check for assets that are using a path instead of a URL, but it seems like a fair amount of work.

**Comment by bennypowers** [comment]
you could just use convention, if it's not a fully qualified url, you can use raw.githubusercontent.com
